# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of>
success_symbol = "[](bold blue)"     # The "success>
error_symbol = "[](bold red)"
